
package visao;

import dao.CategoriaDAO;
import dao.ProdutoDAO;
import dao.db.DbException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Categoria;

/**
 *
 * @author João Pedro Maziero
 */
public class FrmAlterarPreco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlterarPreco.class.getName());

    private List<Categoria> categorias = new ArrayList<>();

    public FrmAlterarPreco() {
        initComponents();
        setLocationRelativeTo(null);
        carregarCategorias();
        b_Aumentar.addActionListener(this::b_AumentarActionPerformed);
    }

    /** Carrega categorias do banco e popula o ComboBox, com opção "Todas" no início. */
    private void carregarCategorias() {
        try {
            categorias = new CategoriaDAO().listarTodos();
            cb_categoria.removeAllItems();
            cb_categoria.addItem("Todas");
            for (Categoria c : categorias) {
                cb_categoria.addItem(c.getNome());
            }
        } catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar categorias: " + e.getMessage());
        }
    }

    /**
     * Lógica comum de reajuste: valida o percentual e chama o DAO.
     *
     * @param aumentar {@code true} para aumento, {@code false} para desconto.
     */
    private void processarReajuste(boolean aumentar) {
        String texto = c_porcentagem.getText().trim();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o percentual.");
            return;
        }
        double percentual;
        try {
            percentual = Double.parseDouble(texto.replace(",", "."));
            if (percentual <= 0 || percentual > 100) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Percentual inválido. Use um número entre 0 e 100.");
            return;
        }

        double fator = aumentar ? (1 + percentual / 100) : (1 - percentual / 100);

        // índice 0 = "Todas"; índices 1..n = categorias[i-1]
        int selectedIndex = cb_categoria.getSelectedIndex();
        int categoriaId = selectedIndex == 0 ? -1 : categorias.get(selectedIndex - 1).getId();

        String escopo = selectedIndex == 0 ? "todos os produtos" : "produtos da categoria \"" + cb_categoria.getSelectedItem() + "\"";
        String operacao = aumentar ? "Aumentar" : "Descontar";

        int confirmacao = JOptionPane.showConfirmDialog(
            null,
            operacao + " " + percentual + "% em " + escopo + "?",
            "Confirmar reajuste",
            JOptionPane.YES_NO_OPTION
        );
        if (confirmacao != JOptionPane.YES_OPTION) return;

        try {
            new ProdutoDAO().reajustarPrecos(fator, categoriaId);
            JOptionPane.showMessageDialog(null, "Preços atualizados com sucesso!");
            c_porcentagem.setText("");
        } catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar preços: " + e.getMessage());
        }
    }

    private void b_AumentarActionPerformed(java.awt.event.ActionEvent evt) {
        processarReajuste(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        c_porcentagem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        b_Sair = new javax.swing.JButton();
        b_Descontar = new javax.swing.JButton();
        b_Aumentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Preços");

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Categoria:");

        c_porcentagem.addActionListener(this::c_porcentagemActionPerformed);

        jLabel2.setText("%");

        b_Sair.setText("Sair");
        b_Sair.addActionListener(this::b_SairActionPerformed);

        b_Descontar.setText("Descontar");
        b_Descontar.addActionListener(this::b_DescontarActionPerformed);

        b_Aumentar.setText("Aumentar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_Aumentar)
                        .addGap(12, 12, 12)
                        .addComponent(b_Descontar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_Sair)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(c_porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Sair)
                    .addComponent(b_Descontar)
                    .addComponent(b_Aumentar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_porcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_porcentagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_porcentagemActionPerformed

    private void b_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_SairActionPerformed

    private void b_DescontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_DescontarActionPerformed
        processarReajuste(false);
    }//GEN-LAST:event_b_DescontarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAlterarPreco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Aumentar;
    private javax.swing.JButton b_Descontar;
    private javax.swing.JButton b_Sair;
    private javax.swing.JTextField c_porcentagem;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
