package visao;

import dao.CategoriaDAO;
import dao.db.DbException;
import javax.swing.JOptionPane;
import modelo.Categoria;

/**
 * Tela de gerenciamento de categorias do sistema de estoque.
 * <p>
 * Permite ao usuário cadastrar, alterar, excluir e buscar categorias. Os dados
 * são carregados do banco de dados via {@link CategoriaDAO} e exibidos em uma
 * tabela interativa.
 * </p>
 *
 * @author Pedro Henrique
 */
public class FrmGerenciarCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName());

    /**
     * Construtor da tela de Gerenciar Categorias. Inicializa os componentes,
     * centraliza a tela, desabilita os botões Alterar e Excluir e carrega os
     * dados da tabela.
     */
    public FrmGerenciarCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jBAlterarGC.setEnabled(false); // desabilita Alterar
        jBExcluirGC.setEnabled(false); // desabilita Excluir
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGerenciarCategorias = new javax.swing.JLabel();
        jBNovoGC = new javax.swing.JButton();
        jBAlterarGC = new javax.swing.JButton();
        jBExcluirGC = new javax.swing.JButton();
        jBVoltarGC = new javax.swing.JButton();
        jTFNomeCategoriaGC = new javax.swing.JTextField();
        jCBTipoTamanhoGC = new javax.swing.JComboBox<>();
        jCBTipoEmbalagemGC = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBBuscarGC = new javax.swing.JButton();
        JBSalvarGC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLGerenciarCategorias.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLGerenciarCategorias.setText("Gerenciar Categorias");
        jLGerenciarCategorias.setPreferredSize(new java.awt.Dimension(200, 18));

        jBNovoGC.setText("Novo");
        jBNovoGC.addActionListener(this::jBNovoGCActionPerformed);

        jBAlterarGC.setText("Alterar");
        jBAlterarGC.addActionListener(this::jBAlterarGCActionPerformed);

        jBExcluirGC.setText("Excluir");
        jBExcluirGC.addActionListener(this::jBExcluirGCActionPerformed);

        jBVoltarGC.setText("Voltar");
        jBVoltarGC.addActionListener(this::jBVoltarGCActionPerformed);

        jTFNomeCategoriaGC.addActionListener(this::jTFNomeCategoriaGCActionPerformed);

        jCBTipoTamanhoGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Medio", "Grande" }));
        jCBTipoTamanhoGC.addActionListener(this::jCBTipoTamanhoGCActionPerformed);

        jCBTipoEmbalagemGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "Vidro", "Plástico" }));
        jCBTipoEmbalagemGC.addActionListener(this::jCBTipoEmbalagemGCActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tamanho", "Embalagem"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jBBuscarGC.setText("Buscar:");
        jBBuscarGC.addActionListener(this::jBBuscarGCActionPerformed);

        JBSalvarGC.setText("Salvar");
        JBSalvarGC.addActionListener(this::JBSalvarGCActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(166, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBNovoGC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBSalvarGC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBAlterarGC)
                                .addGap(18, 18, 18)
                                .addComponent(jBExcluirGC))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBBuscarGC, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addGap(26, 26, 26)
                .addComponent(jBVoltarGC)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscarGC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNovoGC)
                    .addComponent(JBSalvarGC)
                    .addComponent(jBAlterarGC)
                    .addComponent(jBExcluirGC)
                    .addComponent(jBVoltarGC))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /**
     * Limpa todos os campos do formulário e desabilita os botões Alterar e
     * Excluir. Move o foco para o campo Nome, deixando a tela pronta para um
     * novo cadastro.
     *
     * @param evt evento de clique no botão Novo
     */
    private void jBNovoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoGCActionPerformed
        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);
        this.jTFNomeCategoriaGC.requestFocus();
        jBAlterarGC.setEnabled(false); // desabilita ao limpar
        jBExcluirGC.setEnabled(false); // desabilita ao limpar
    }//GEN-LAST:event_jBNovoGCActionPerformed
    /**
     * Exclui a categoria selecionada na tabela após confirmação do usuário.
     * Solicita confirmação antes de executar a exclusão no banco de dados.
     * Recarrega a tabela e desabilita os botões Alterar e Excluir após excluir.
     *
     * @param evt evento de clique no botão Excluir
     */
    private void jBExcluirGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirGCActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria na tabela!");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

        int confirmacao = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                new CategoriaDAO().deletar(id);
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                jBAlterarGC.setEnabled(false);
                jBExcluirGC.setEnabled(false);
                carregaTabela();
            } catch (DbException e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jBExcluirGCActionPerformed
    /**
     * @param evt evento do ComboBox de tamanho
     */
    private void jCBTipoTamanhoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoTamanhoGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoTamanhoGCActionPerformed
    /**
     * Fecha a tela atual e retorna ao menu principal.
     *
     * @param evt evento de clique no botão Voltar
     */
    private void jBVoltarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarGCActionPerformed

        this.dispose();
    }//GEN-LAST:event_jBVoltarGCActionPerformed
    /**
     * @param evt evento do ComboBox de embalagem
     */
    private void jCBTipoEmbalagemGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoEmbalagemGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoEmbalagemGCActionPerformed
    /**
     * @param evt evento do campo de texto Nome
     */
    private void jTFNomeCategoriaGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeCategoriaGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeCategoriaGCActionPerformed
    /**
     * Filtra as categorias exibidas na tabela com base nos critérios
     * informados.
     * <p>
     * A busca por nome é parcial e sem distinção de maiúsculas/minúsculas. Os
     * filtros de tamanho e embalagem são ignorados quando a opção "Todos" está
     * selecionada. Exibe mensagem caso nenhuma categoria seja encontrada.
     * </p>
     *
     * @param evt evento de clique no botão Buscar
     */
    private void jBBuscarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarGCActionPerformed
        String nomeBusca = this.jTFNomeCategoriaGC.getText().toLowerCase();
        String tamanhoBusca = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalageBusca = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (modelo.Categoria cat : listaCategorias) {
            boolean nomeOk = nomeBusca.isEmpty() || cat.getNome().toLowerCase().contains(nomeBusca);
            boolean tamanhoOk = tamanhoBusca.equals("Todos") || cat.getTamanho().equals(tamanhoBusca);
            boolean embalagemOk = embalageBusca.equals("Todos") || cat.getEmbalagem().equals(embalageBusca);

            if (nomeOk && tamanhoOk && embalagemOk) {
                modelo.addRow(new Object[]{
                    cat.getId(),
                    cat.getNome(),
                    cat.getTamanho(),
                    cat.getEmbalagem()
                });
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma categoria encontrada!");
        }
    }//GEN-LAST:event_jBBuscarGCActionPerformed
    /**
     * Altera os dados da categoria selecionada na tabela.
     * <p>
     * Valida se uma linha está selecionada e se o nome tem ao menos 2
     * caracteres. Verifica se já existe outra categoria com os mesmos dados
     * antes de alterar. Atualiza o registro no banco de dados via
     * {@link CategoriaDAO}.
     * </p>
     *
     * @param evt evento de clique no botão Alterar
     */
    private void jBAlterarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarGCActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria para alterar!");
            return;
        }

        String nome = this.jTFNomeCategoriaGC.getText();
        String tamanho = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalagem = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        if (nome.length() < 2) {
            JOptionPane.showMessageDialog(null, "Nome deve conter ao menos 2 caracteres.");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

        try {
            modelo.Categoria cat = new modelo.Categoria(id, nome, tamanho, embalagem);
            new CategoriaDAO().atualizar(cat);
            JOptionPane.showMessageDialog(null, "Categoria alterada com sucesso!");
        } catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar: " + e.getMessage());
            return;
        }

        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);
        jBAlterarGC.setEnabled(false);
        jBExcluirGC.setEnabled(false);
        carregaTabela();
    }//GEN-LAST:event_jBAlterarGCActionPerformed
    /**
     * Cadastra uma nova categoria no banco de dados.
     * <p>
     * Valida se o nome tem ao menos 2 caracteres e verifica duplicatas
     * considerando nome, tamanho e embalagem em conjunto antes de salvar.
     * Recarrega a tabela após o cadastro bem sucedido.
     * </p>
     *
     * @param evt evento de clique no botão Salvar
     */
    private void JBSalvarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarGCActionPerformed
        String nome = this.jTFNomeCategoriaGC.getText();
        String tamanho = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalagem = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        if (nome.length() < 2) {
            JOptionPane.showMessageDialog(null, "Nome deve conter ao menos 2 caracteres.");
            return;
        }

        for (modelo.Categoria c : listaCategorias) {
            if (c.getNome().equalsIgnoreCase(nome)
                    && c.getTamanho().equalsIgnoreCase(tamanho)
                    && c.getEmbalagem().equalsIgnoreCase(embalagem)) {
                JOptionPane.showMessageDialog(null, "Já existe uma categoria com esse nome!");
                return;
            }
        }
        try {
            modelo.Categoria cat = new modelo.Categoria(nome, tamanho, embalagem);
            new CategoriaDAO().inserir(cat);
            JOptionPane.showMessageDialog(null, "Categoria cadastrada com sucesso!");
        } catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
            return;
        }

        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);

        carregaTabela();
    }//GEN-LAST:event_JBSalvarGCActionPerformed
    /**
     * Preenche os campos do formulário com os dados da linha selecionada na
     * tabela. Habilita os botões Alterar e Excluir ao selecionar uma linha.
     *
     * @param evt evento de clique do mouse na tabela
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada != -1) {
            this.jTFNomeCategoriaGC.setText(jTable1.getValueAt(linhaSelecionada, 1).toString());
            this.jCBTipoTamanhoGC.setSelectedItem(jTable1.getValueAt(linhaSelecionada, 2).toString());
            this.jCBTipoEmbalagemGC.setSelectedItem(jTable1.getValueAt(linhaSelecionada, 3).toString());
            jBAlterarGC.setEnabled(true);
            jBExcluirGC.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * Método principal para execução standalone da tela. Configura o look and
     * feel Nimbus e exibe a tela.
     *
     * @param args argumentos de linha de comando (não utilizados)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGerenciarCategoria().setVisible(true));
    }
    /**
     * Lista em memória com todas as categorias carregadas do banco de dados.
     * Utilizada para operações de busca e controle sem consultas adicionais ao
     * banco.
     */
    private java.util.List<modelo.Categoria> listaCategorias = new java.util.ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvarGC;
    private javax.swing.JButton jBAlterarGC;
    private javax.swing.JButton jBBuscarGC;
    private javax.swing.JButton jBExcluirGC;
    private javax.swing.JButton jBNovoGC;
    private javax.swing.JButton jBVoltarGC;
    private javax.swing.JComboBox<String> jCBTipoEmbalagemGC;
    private javax.swing.JComboBox<String> jCBTipoTamanhoGC;
    private javax.swing.JLabel jLGerenciarCategorias;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNomeCategoriaGC;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 /**
     * Carrega todas as categorias do banco de dados e popula a tabela.
     * <p>
     * Atualiza o {@code listaCategorias} com os dados mais recentes do banco e
     * exibe cada categoria como uma linha na tabela. Exibe mensagem de erro
     * caso ocorra falha na conexão ou consulta ao banco.
     * </p>
     */
    private void carregaTabela() {
        try {
            listaCategorias = new CategoriaDAO().listarTodos();
        } catch (DbException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar categorias: " + e.getMessage());
            return;
        }
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (modelo.Categoria cat : listaCategorias) {
            modelo.addRow(new Object[]{
                cat.getId(),
                cat.getNome(),
                cat.getTamanho(),
                cat.getEmbalagem()
            });
        }
    }
}
