package visao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;


public class FrmRelatorios extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRelatorios.class.getName());

    /**
     * Creates new form FrmRelatorios
     */
    public FrmRelatorios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("RELATÓRIOS");
        jLabel1.setName(""); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Preços", "Balanço Financeiro", "Estoque abaixo do minimo", "Produto com maior entrada", "Produto com maior saida", "Produto por categoria" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Relatório:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Arquivo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton1.setText("BAIXAR RELATÓRIO PDF");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Sair");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String tipoRelatorio = jComboBox2.getSelectedItem().toString();

    try {
        java.sql.Connection conn = dao.db.Database.getConnection();
        String sql = "";

        if (tipoRelatorio.equals("Lista de Preços")) {
        sql = "SELECT nome, preco_unitario FROM produtos ORDER BY nome ASC";
        } 
        else if (tipoRelatorio.equals("Estoque abaixo do minimo")) {
        sql = "SELECT nome, quantidade_estoque, quantidade_minima FROM produtos WHERE quantidade_estoque < quantidade_minima";
        }
        else if (tipoRelatorio.equals("Produto com maior entrada")) {
        sql = "SELECT nome, SUM(qtd) AS total_entrada FROM movimentacoes WHERE movimentacao = 'Entrada' GROUP BY nome ORDER BY total_entrada DESC";
        }
        else if (tipoRelatorio.equals("Produto com maior saida")) {
        sql = "SELECT nome, SUM(qtd) AS total_saida FROM movimentacoes WHERE movimentacao = 'Saida' GROUP BY nome ORDER BY total_saida DESC";
        }
        else if (tipoRelatorio.equals("Balanço Financeiro")) {
        sql = "SELECT nome, preco_unitario, quantidade_estoque, (preco_unitario * quantidade_estoque) AS total FROM produtos ORDER BY nome ASC";
        }
        else if (tipoRelatorio.equals("Produto por categoria")) {
        sql = "SELECT c.nome, COUNT(DISTINCT p.id) AS total FROM categorias c JOIN produtos p ON p.categoria_id = c.id GROUP BY c.nome ORDER BY c.nome";
        }
            
          
        else {
        JOptionPane.showMessageDialog(this, "Relatório ainda não implementado");
        return;
        }

        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery();

        org.apache.pdfbox.pdmodel.PDDocument document = new org.apache.pdfbox.pdmodel.PDDocument();
        org.apache.pdfbox.pdmodel.PDPage page = new org.apache.pdfbox.pdmodel.PDPage();
        document.addPage(page);

        org.apache.pdfbox.pdmodel.PDPageContentStream content =
        new org.apache.pdfbox.pdmodel.PDPageContentStream(document, page);

        content.beginText();
        content.setFont(org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA_BOLD, 14);
        content.newLineAtOffset(50, 750);
        content.showText("RELATÓRIO: " + tipoRelatorio);
        content.endText();

        int y = 700;

        while (rs.next()) {

            content.beginText();
            content.setFont(org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA, 12);
            content.newLineAtOffset(50, y);

            String linha = rs.getString(1);

            if (tipoRelatorio.equals("Lista de Preços")) {
                linha += " - R$ " + rs.getDouble(2);
            }

            if (tipoRelatorio.equals("Estoque abaixo do minimo")) {
                linha += " | Estoque: " + rs.getInt(2) +
                         " | Min: " + rs.getInt(3);
            }
            
            if (tipoRelatorio.equals("Produto com maior entrada")) {
                linha += " | Total Entrada: " + rs.getInt(2);
            }
            
            if (tipoRelatorio.equals("Produto com maior saida")) {
                 linha += " | Total Saída: " + rs.getInt(2);
            }
            if (tipoRelatorio.equals("Balanço Financeiro")) {

                linha += " | Preço: R$ " + rs.getDouble(2)
                 + " | Estoque: " + rs.getInt(3)
                 + " | Total: R$ " + rs.getDouble(4);
            }
            if (tipoRelatorio.equals("Produto por categoria")) {
               linha = rs.getString(1) + " | Quantidade: " + rs.getInt(2);
            }
            
            
            content.showText(linha);
            content.endText();

            y -= 20;
        }

        content.close();
        document.save(tipoRelatorio + ".pdf");
        document.close();

        rs.close();
        stmt.close();

        JOptionPane.showMessageDialog(this, "PDF gerado com sucesso!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao gerar PDF: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    FrmaMenuPrincipal menu = new FrmaMenuPrincipal();
    menu.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     java.awt.EventQueue.invokeLater(() -> new FrmRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
