/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CategoriaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FrmGerenciarCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName());

    /**
     * Creates new form FrmGerenciarCategoria
     */
    public FrmGerenciarCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGerenciarCategorias = new javax.swing.JLabel();
        jBNovoGC = new javax.swing.JButton();
        jBAlterarGC = new javax.swing.JButton();
        jBExcluirGC = new javax.swing.JButton();
        jBVoltarGC = new javax.swing.JButton();
        jLBuscarCategoriaGC = new javax.swing.JLabel();
        jTFNomeCategoriaGC = new javax.swing.JTextField();
        jCBTipoTamanhoGC = new javax.swing.JComboBox<>();
        jCBTipoEmbalagemGC = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLGerenciarCategorias.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLGerenciarCategorias.setText("Gerenciar Categorias");
        jLGerenciarCategorias.setPreferredSize(new java.awt.Dimension(200, 18));

        jBNovoGC.setText("Novo");
        jBNovoGC.addActionListener(this::jBNovoGCActionPerformed);

        jBAlterarGC.setText("Alterar");

        jBExcluirGC.setText("Excluir");
        jBExcluirGC.addActionListener(this::jBExcluirGCActionPerformed);

        jBVoltarGC.setText("Voltar");
        jBVoltarGC.addActionListener(this::jBVoltarGCActionPerformed);

        jLBuscarCategoriaGC.setText("Buscar Categorias:");

        jCBTipoTamanhoGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Medio", "Grande" }));
        jCBTipoTamanhoGC.addActionListener(this::jCBTipoTamanhoGCActionPerformed);

        jCBTipoEmbalagemGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "Vidro", "Plástico" }));
        jCBTipoEmbalagemGC.addActionListener(this::jCBTipoEmbalagemGCActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tamanho", "Embalagem"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jBNovoGC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLBuscarCategoriaGC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBAlterarGC)
                                    .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jBExcluirGC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBVoltarGC))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVoltarGC)
                    .addComponent(jBExcluirGC)
                    .addComponent(jBAlterarGC)
                    .addComponent(jBNovoGC))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBuscarCategoriaGC)
                    .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNovoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNovoGCActionPerformed

    private void jBExcluirGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirGCActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        // Verifica se alguma linha foi selecionada
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria na tabela!");
            return;
        }

        // Pega o id da linha selecionada (coluna 0 = ID)
        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

        int confirmacao = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                CategoriaDAO dao = new CategoriaDAO();
                dao.deletar(id);
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jBExcluirGCActionPerformed

    private void jCBTipoTamanhoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoTamanhoGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoTamanhoGCActionPerformed

    private void jBVoltarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarGCActionPerformed
        FrmaMenuPrincipal janela = new FrmaMenuPrincipal();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVoltarGCActionPerformed

    private void jCBTipoEmbalagemGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoEmbalagemGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoEmbalagemGCActionPerformed

    /**
     * @param args the command line arguments
     */
    // CORRETO
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGerenciarCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarGC;
    private javax.swing.JButton jBExcluirGC;
    private javax.swing.JButton jBNovoGC;
    private javax.swing.JButton jBVoltarGC;
    private javax.swing.JComboBox<String> jCBTipoEmbalagemGC;
    private javax.swing.JComboBox<String> jCBTipoTamanhoGC;
    private javax.swing.JLabel jLBuscarCategoriaGC;
    private javax.swing.JLabel jLGerenciarCategorias;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNomeCategoriaGC;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
