/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CategoriaDAO;
import dao.db.DbException;
import javax.swing.JOptionPane;
import model.Categoria;

/**
 *
 * @author pedro
 */
public class FrmGerenciarCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName());

    /**
     * Creates new form FrmGerenciarCategoria
     */
    public FrmGerenciarCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jBAlterarGC.setEnabled(false); // desabilita Alterar
        jBExcluirGC.setEnabled(false); // desabilita Excluir
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGerenciarCategorias = new javax.swing.JLabel();
        jBNovoGC = new javax.swing.JButton();
        jBAlterarGC = new javax.swing.JButton();
        jBExcluirGC = new javax.swing.JButton();
        jBVoltarGC = new javax.swing.JButton();
        jTFNomeCategoriaGC = new javax.swing.JTextField();
        jCBTipoTamanhoGC = new javax.swing.JComboBox<>();
        jCBTipoEmbalagemGC = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBBuscarGC = new javax.swing.JButton();
        JBSalvarGC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLGerenciarCategorias.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLGerenciarCategorias.setText("Gerenciar Categorias");
        jLGerenciarCategorias.setPreferredSize(new java.awt.Dimension(200, 18));

        jBNovoGC.setText("Novo");
        jBNovoGC.addActionListener(this::jBNovoGCActionPerformed);

        jBAlterarGC.setText("Alterar");
        jBAlterarGC.addActionListener(this::jBAlterarGCActionPerformed);

        jBExcluirGC.setText("Excluir");
        jBExcluirGC.addActionListener(this::jBExcluirGCActionPerformed);

        jBVoltarGC.setText("Voltar");
        jBVoltarGC.addActionListener(this::jBVoltarGCActionPerformed);

        jTFNomeCategoriaGC.addActionListener(this::jTFNomeCategoriaGCActionPerformed);

        jCBTipoTamanhoGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Medio", "Grande" }));
        jCBTipoTamanhoGC.addActionListener(this::jCBTipoTamanhoGCActionPerformed);

        jCBTipoEmbalagemGC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "Vidro", "Plástico" }));
        jCBTipoEmbalagemGC.addActionListener(this::jCBTipoEmbalagemGCActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tamanho", "Embalagem"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jBBuscarGC.setText("Buscar:");
        jBBuscarGC.addActionListener(this::jBBuscarGCActionPerformed);

        JBSalvarGC.setText("Salvar");
        JBSalvarGC.addActionListener(this::JBSalvarGCActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBBuscarGC)
                                .addGap(18, 18, 18)
                                .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBNovoGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBSalvarGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAlterarGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBExcluirGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBVoltarGC)
                        .addGap(213, 213, 213))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLGerenciarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAlterarGC)
                    .addComponent(jBExcluirGC)
                    .addComponent(jBVoltarGC)
                    .addComponent(jBNovoGC)
                    .addComponent(JBSalvarGC))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoTamanhoGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoEmbalagemGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomeCategoriaGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarGC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNovoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoGCActionPerformed
        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);
        this.jTFNomeCategoriaGC.requestFocus();
        jBAlterarGC.setEnabled(false); // desabilita ao limpar
        jBExcluirGC.setEnabled(false); // desabilita ao limpar
    }//GEN-LAST:event_jBNovoGCActionPerformed

    private void jBExcluirGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirGCActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        // Verifica se alguma linha foi selecionada
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria na tabela!");
            return;
        }

        // Pega o id da linha selecionada (coluna 0 = ID)
        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

        int confirmacao = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                CategoriaDAO dao = new CategoriaDAO();
                dao.deletar(id);
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
            } catch (DbException e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jBExcluirGCActionPerformed

    private void jCBTipoTamanhoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoTamanhoGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoTamanhoGCActionPerformed

    private void jBVoltarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarGCActionPerformed

        this.dispose();
    }//GEN-LAST:event_jBVoltarGCActionPerformed

    private void jCBTipoEmbalagemGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoEmbalagemGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoEmbalagemGCActionPerformed

    private void jTFNomeCategoriaGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeCategoriaGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeCategoriaGCActionPerformed

    private void jBBuscarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarGCActionPerformed
        String nomeBusca = this.jTFNomeCategoriaGC.getText().toLowerCase();
        String tamanhoBusca = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalageBusca = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (model.Categoria cat : listaCategorias) {
            boolean nomeOk = nomeBusca.isEmpty() || cat.getNome().toLowerCase().contains(nomeBusca);
            boolean tamanhoOk = tamanhoBusca.equals("Todos") || cat.getTamanho().equals(tamanhoBusca);
            boolean embalagemOk = embalageBusca.equals("Todos") || cat.getEmbalagem().equals(embalageBusca);

            if (nomeOk && tamanhoOk && embalagemOk) {
                modelo.addRow(new Object[]{
                    listaCategorias.indexOf(cat) + 1,
                    cat.getNome(),
                    cat.getTamanho(),
                    cat.getEmbalagem()
                });
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma categoria encontrada!");
        }
    }//GEN-LAST:event_jBBuscarGCActionPerformed

    private void jBAlterarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarGCActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria para alterar!");
            return;
        }

        String nome = this.jTFNomeCategoriaGC.getText();
        String tamanho = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalagem = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        if (nome.length() < 2) {
            JOptionPane.showMessageDialog(null, "Nome deve conter ao menos 2 caracteres.");
            return;
        }

        for (int i = 0; i < listaCategorias.size(); i++) {
            if (listaCategorias.get(i).getNome().equalsIgnoreCase(nome)
                    && listaCategorias.get(i).getTamanho().equalsIgnoreCase(tamanho)
                    && listaCategorias.get(i).getEmbalagem().equalsIgnoreCase(embalagem)
                    && i != linhaSelecionada) {
                JOptionPane.showMessageDialog(null, "Já existe uma categoria com esse nome!");
                return;
            }
        }
        model.Categoria cat = listaCategorias.get(linhaSelecionada);
        cat.setNome(nome);
        cat.setTamanho(tamanho);
        cat.setEmbalagem(embalagem);

        JOptionPane.showMessageDialog(null, "Categoria alterada com sucesso!");

        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);

        carregaTabela();
    }//GEN-LAST:event_jBAlterarGCActionPerformed

    private void JBSalvarGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarGCActionPerformed
        String nome = this.jTFNomeCategoriaGC.getText();
        String tamanho = this.jCBTipoTamanhoGC.getSelectedItem().toString();
        String embalagem = this.jCBTipoEmbalagemGC.getSelectedItem().toString();

        if (nome.length() < 2) {
            JOptionPane.showMessageDialog(null, "Nome deve conter ao menos 2 caracteres.");
            return;
        }

        for (model.Categoria c : listaCategorias) {
            if (c.getNome().equalsIgnoreCase(nome)
                    && c.getTamanho().equalsIgnoreCase(tamanho)
                    && c.getEmbalagem().equalsIgnoreCase(embalagem)) {
                JOptionPane.showMessageDialog(null, "Já existe uma categoria com esse nome!");
                return;
            }
        }
        model.Categoria cat = new model.Categoria(nome, tamanho, embalagem);
        listaCategorias.add(cat);
        JOptionPane.showMessageDialog(null, "Categoria cadastrada com sucesso!");

        this.jTFNomeCategoriaGC.setText("");
        this.jCBTipoTamanhoGC.setSelectedIndex(0);
        this.jCBTipoEmbalagemGC.setSelectedIndex(0);

        carregaTabela();
    }//GEN-LAST:event_JBSalvarGCActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada != -1) {
            model.Categoria cat = listaCategorias.get(linhaSelecionada);
            this.jTFNomeCategoriaGC.setText(cat.getNome());
            this.jCBTipoTamanhoGC.setSelectedItem(cat.getTamanho());
            this.jCBTipoEmbalagemGC.setSelectedItem(cat.getEmbalagem());

            // habilita os botões ao selecionar uma linha
            jBAlterarGC.setEnabled(true);
            jBExcluirGC.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    // CORRETO
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGerenciarCategoria().setVisible(true));
    }
    private static java.util.ArrayList<model.Categoria> listaCategorias = new java.util.ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvarGC;
    private javax.swing.JButton jBAlterarGC;
    private javax.swing.JButton jBBuscarGC;
    private javax.swing.JButton jBExcluirGC;
    private javax.swing.JButton jBNovoGC;
    private javax.swing.JButton jBVoltarGC;
    private javax.swing.JComboBox<String> jCBTipoEmbalagemGC;
    private javax.swing.JComboBox<String> jCBTipoTamanhoGC;
    private javax.swing.JLabel jLGerenciarCategorias;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNomeCategoriaGC;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregaTabela() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (model.Categoria cat : listaCategorias) {
            modelo.addRow(new Object[]{
                listaCategorias.indexOf(cat) + 1,
                cat.getNome(),
                cat.getTamanho(),
                cat.getEmbalagem()
            });
        }
    }
}
